// QuarkSketch prompt pools
// 200 subjects and 200 actions for high round-to-round variety.
(function initPrompts(global) {
  const subjects = [
    "astronaut",
    "alien",
    "robot",
    "pirate",
    "ninja",
    "wizard",
    "knight",
    "dragon",
    "unicorn",
    "mermaid",
    "vampire",
    "werewolf",
    "ghost",
    "zombie",
    "detective",
    "chef",
    "doctor",
    "scientist",
    "teacher",
    "pilot",
    "firefighter",
    "lifeguard",
    "beekeeper",
    "farmer",
    "musician",
    "dancer",
    "gamer",
    "streamer",
    "inventor",
    "explorer",
    "penguin",
    "otter",
    "fox",
    "wolf",
    "bear",
    "tiger",
    "lion",
    "elephant",
    "giraffe",
    "koala",
    "kangaroo",
    "sloth",
    "owl",
    "eagle",
    "flamingo",
    "peacock",
    "parrot",
    "duck",
    "goose",
    "swan",
    "shark",
    "dolphin",
    "whale",
    "octopus",
    "jellyfish",
    "starfish",
    "crab",
    "lobster",
    "seahorse",
    "pufferfish",
    "chameleon",
    "iguana",
    "crocodile",
    "alligator",
    "frog",
    "toad",
    "snail",
    "butterfly",
    "dragonfly",
    "ladybug",
    "bumblebee",
    "ant",
    "spider",
    "raccoon",
    "hedgehog",
    "hamster",
    "guinea pig",
    "rabbit",
    "deer",
    "moose",
    "boar",
    "yak",
    "alpaca",
    "llama",
    "camel",
    "reindeer",
    "polar bear",
    "snowman",
    "gingerbread man",
    "toy soldier",
    "marionette",
    "clown",
    "juggler",
    "magician",
    "acrobat",
    "surfer",
    "skater",
    "cyclist",
    "hiker",
    "archer",
    "samurai",
    "cowboy",
    "cowgirl",
    "space cat",
    "space dog",
    "cat",
    "dog",
    "hamster astronaut",
    "time traveler",
    "superhero",
    "villain",
    "princess",
    "prince",
    "queen",
    "king",
    "court jester",
    "blacksmith",
    "carpenter",
    "potter",
    "tailor",
    "baker",
    "barista",
    "mail carrier",
    "librarian",
    "engineer",
    "mechanic",
    "plumber",
    "electrician",
    "gardener",
    "florist",
    "photographer",
    "filmmaker",
    "news reporter",
    "archaeologist",
    "paleontologist",
    "astronomer",
    "meteorologist",
    "race car driver",
    "train conductor",
    "bus driver",
    "taxi driver",
    "delivery rider",
    "mountain goat",
    "squirrel",
    "chipmunk",
    "ferret",
    "badger",
    "mole",
    "beaver",
    "seal",
    "walrus",
    "narwhal",
    "manta ray",
    "squid",
    "orca",
    "rhino",
    "hippo",
    "zebra",
    "buffalo",
    "cheetah",
    "panther",
    "leopard",
    "hyena",
    "meerkat",
    "lemur",
    "gorilla",
    "chimpanzee",
    "orangutan",
    "panda",
    "red panda",
    "toucan",
    "woodpecker",
    "crow",
    "raven",
    "pigeon",
    "seagull",
    "pelican",
    "stingray",
    "carp",
    "goldfish",
    "koi",
    "anglerfish",
    "phoenix",
    "griffin",
    "centaur",
    "minotaur",
    "cyclops",
    "goblin",
    "fairy",
    "elf",
    "dwarf",
    "giant",
    "space whale",
    "lava monster",
    "ice golem",
    "cloud spirit",
    "tree guardian",
    "clockwork owl",
    "city bus",
    "paper airplane"
  ];

  const actions = [
    "juggling flaming torches",
    "riding a skateboard downhill",
    "balancing on a giant pizza",
    "dancing in the rain",
    "baking cookies",
    "playing electric guitar",
    "painting a mural",
    "flying a kite",
    "building a treehouse",
    "reading a map upside down",
    "surfing a tidal wave",
    "eating spaghetti",
    "blowing giant bubbles",
    "watering a cactus",
    "carrying too many books",
    "hula hooping",
    "drinking bubble tea",
    "playing chess",
    "hiding behind a lamp",
    "doing a backflip",
    "spinning a basketball",
    "singing opera",
    "jumping over puddles",
    "taking a selfie",
    "folding paper cranes",
    "typing on a tiny laptop",
    "playing table tennis",
    "walking a balloon dog",
    "ice skating",
    "skiing backwards",
    "snowboarding",
    "building a snow fort",
    "sledding down a hill",
    "making a sandcastle",
    "scuba diving",
    "snorkeling",
    "kayaking",
    "paddling a canoe",
    "racing a shopping cart",
    "driving a go-kart",
    "fixing a spaceship",
    "launching fireworks",
    "planting sunflowers",
    "chasing butterflies",
    "feeding ducks",
    "playing hide and seek",
    "solving a maze",
    "escaping quicksand",
    "climbing a ladder",
    "swinging on a vine",
    "walking a tightrope",
    "doing yoga",
    "meditating",
    "lifting tiny dumbbells",
    "bench pressing a cloud",
    "hammering nails",
    "sewing a cape",
    "knitting a scarf",
    "drumming on buckets",
    "conducting an orchestra",
    "playing the violin",
    "playing the flute",
    "playing the trumpet",
    "blowing a saxophone",
    "writing a poem",
    "studying for an exam",
    "taking notes",
    "spilling coffee",
    "carrying groceries",
    "riding a unicycle",
    "walking stilts",
    "catching a frisbee",
    "throwing a boomerang",
    "flying a drone",
    "taking moon rocks home",
    "pushing a giant button",
    "opening a treasure chest",
    "digging for fossils",
    "hatching an egg",
    "brushing giant teeth",
    "washing a car",
    "vacuuming the ceiling",
    "mopping a rainbow",
    "washing windows",
    "peeling a banana",
    "flipping pancakes",
    "grilling burgers",
    "making sushi",
    "decorating cupcakes",
    "mixing a potion",
    "stirring a cauldron",
    "casting a spell",
    "shooting arrows",
    "swinging a sword",
    "raising a shield",
    "fencing",
    "playing soccer",
    "kicking a field goal",
    "pitching a baseball",
    "shooting hoops",
    "serving a volleyball",
    "lifting a trophy",
    "waving from a parade float",
    "marching in a band",
    "wrestling an octopus",
    "tickling a dragon",
    "sneaking through lasers",
    "hacking a vending machine",
    "walking through a portal",
    "time traveling",
    "teleporting",
    "hovering above the ground",
    "moonwalking",
    "doing the worm dance",
    "breakdancing",
    "tap dancing",
    "ballet dancing",
    "line dancing",
    "cheering at a concert",
    "selling lemonade",
    "running a food truck",
    "delivering pizza",
    "mailing a giant letter",
    "stamping passports",
    "guiding a tour group",
    "discovering a hidden cave",
    "camping under stars",
    "toasting marshmallows",
    "starting a campfire",
    "telling ghost stories",
    "chasing a runaway hat",
    "fishing in a puddle",
    "lifting a boulder",
    "rolling downhill",
    "dodging meteors",
    "surfing on lava",
    "building a robot",
    "charging batteries",
    "rewiring a machine",
    "coding a game",
    "debugging all night",
    "printing stickers",
    "making pottery",
    "carving ice sculptures",
    "blowing glass",
    "gardening on a rooftop",
    "watering floating plants",
    "riding a carousel",
    "winning a claw machine",
    "feeding an arcade token",
    "playing pinball",
    "solving a crossword",
    "stacking dominoes",
    "playing cards",
    "rolling dice",
    "building a pillow fort",
    "jumping on a trampoline",
    "bouncing a pogo stick",
    "walking a slackline",
    "racing snails",
    "painting miniatures",
    "collecting seashells",
    "polishing a crown",
    "guarding a castle",
    "rowing a Viking boat",
    "sailing through a storm",
    "steering a hot air balloon",
    "parachuting",
    "hang gliding",
    "climbing an ice wall",
    "forging a key",
    "unlocking a secret door",
    "escaping a maze",
    "chopping vegetables",
    "making ramen",
    "pouring tea",
    "juggling oranges",
    "catching snowflakes",
    "playing with sparklers",
    "wrapping gifts",
    "decorating a tree",
    "ringing a bell",
    "blowing out candles",
    "opening presents",
    "training for a marathon",
    "sprinting through mud",
    "climbing a mountain",
    "crossing a rope bridge",
    "photographing birds",
    "painting clouds",
    "writing in a diary",
    "reading under a blanket",
    "building a rocket",
    "floating in zero gravity",
    "walking on the moon",
    "repairing a satellite",
    "waving a flag",
    "spinning plates",
    "making shadow puppets",
    "playing with glow sticks"
  ];

  function pick(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  function withArticle(noun) {
    const cleanNoun = noun.trim();
    const firstWord = cleanNoun.split(/\s+/)[0].toLowerCase();

    if (/^(honest|hour|heir|honor)/.test(firstWord)) {
      return `an ${cleanNoun}`;
    }

    if (/^(uni([^nmd]|$)|use|user|ufo|euro)/.test(firstWord)) {
      return `a ${cleanNoun}`;
    }

    if (/^[aeiou]/.test(firstWord)) {
      return `an ${cleanNoun}`;
    }

    return `a ${cleanNoun}`;
  }

  function formatPromptText(subject, action) {
    const cleanAction = action.trim().replace(/\s+/g, " ");
    return `Draw ${withArticle(subject)} ${cleanAction}`;
  }

  function getRandomPrompt() {
    const subject = pick(subjects);
    const action = pick(actions);
    return {
      subject,
      action,
      text: formatPromptText(subject, action)
    };
  }

  global.PROMPTS = {
    subjects,
    actions,
    getRandomPrompt
  };
})(window);
